version: "3.1"

services:
  api:
    container_name: api
    build:
      context: .
    command: npm run start
    restart: always
    volumes:
    - .:/app
    - /app/node_modules
    ports:
    - "3000:3000"
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      - POSTGRES_DB=hibba
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
       - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: always
    depends_on:
      - api

volumes:
  pgdata:
