version: "3.1"

services:
  api:
    container_name: api
    build:
      context: .
    command: npm run start
    restart: always
    ports:
    - "3001:3001"
    depends_on:
      - db
  webserver:
    image: nginx:stable-alpine
    container_name: nginx_conrain
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=hibba
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
