version: "3.1"

services:
  api:
    container_name: api
    build: ./
    command: npm run start
    restart: always
    ports:
    - "3000:3000"
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: hibba
      PG_DATA: /var/lib/postgresql/data
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
