version: "3.1"

services:
  api:
    container_name: api
    build:
      context: .
    command: node dist/src/main.js
    restart: always
    ports:
    - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DO_SPACE_ACCESS_KEY: ${DO_SPACE_ACCESS_KEY}
      DO_SPACE_SECRET_KEY: ${DO_SPACE_SECRET_KEY}
      DO_SPACE_ENDPOINT: ${DO_SPACE_ENDPOINT}
      DO_SPACE_BUCKET: ${DO_SPACE_BUCKET}
  webserver:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=hibba
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
